version: "3"
services:
     
     backend:
         build:
           context: .
         ports:
           - 3000:3000
         command: ["npm","start"] 

     database:
          build:
             image: mysql:5.7
          ports:
             - 3306:3306   
